#!/bin/bash
rm -rf ./.git

PACKAGE_NAME="REPLACE_ME"
DISPLAY_NAME="REPLACE_ME"
DESCRIPTION="REPLACE_ME"

perl -pi -e "s/PACKAGE_NAME/$PACKAGE_NAME/g" $(find . -type f)
perl -pi -e "s/PACKAGE_DISPLAY_NAME/$DISPLAY_NAME/g" $(find . -type f)
perl -pi -e "s/PACKAGE_DESCRIPTION/$DESCRIPTION/g" $(find . -type f)

rm ./setup

git init
git remote add origin git@github.com:tatethurston/$PACKAGE_NAME.git
git branch -M main
git push -u origin main
