#!/bin/bash
rm -rf ./.git

git init

PACKAGE_NAME="REPLACE_ME"
DISPLAY_NAME="REPLACE_ME"
DESCRIPTION="REPLACE_ME"

perl -pi -e "s/PACKAGE_NAME/$PACKAGE_NAME/g" $(rg PACKAGE_NAME -l)
perl -pi -e "s/PACKAGE_DISPLAY_NAME/$DISPLAY_NAME/g" $(rg PACKAGE_DISPLAY_NAME -l)
perl -pi -e "s/PACKAGE_DESCRIPTION/$DESCRIPTION/g" $(rg PACKAGE_DESCRIPTION -l)

rm ./setup

git add

git remote add origin git@github.com:tatethurston/$PACKAGE_NAME.git
git branch -M main
git push --set-upstream origin main
