name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: "Lint and Test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm lint
      - run: pnpm test:ci && pnpm codecov --token=$CODECOV_TOKEN
        env:
          # 1. Get here:
          # https://app.codecov.io/gh/tatethurston/PACKAGE_NAME/settings
          # 2. Upload here:
          # https://github.com/tatethurston/PACKAGE_NAME/settings/secrets/actions/new
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
