name: Publish NPM Package
on:
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16.x"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
      - run: yarn
      - run: yarn package:build
      - run: cd dist && npm publish
        env:
          # 1. Generate a new `automation` token here:
          # https://www.npmjs.com/settings/tatethurston/tokens
          # 2. Upload here:
          # https://github.com/tatethurston/PACKAGE_NAME/settings/secrets/actions/new
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
